#!/bin/sh
# Based on: http://code.google.com/p/panda-buildroot/source/\
# browse/buildroot/package/busybox/S41udhcpc?name=panda-buildroot_V0.2
# /etc/init.d/udhcpc: start or stop udhcpc client

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/sbin/udhcpc

test -x $DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting DHCP client: udhcpc"
    sleep 2 # wait for network comming up
    start-stop-daemon --start -b --quiet --exec $DAEMON \
      -- --script=/usr/share/udhcpc/default.script || echo -n " already running"
    echo "."
  ;;

  restart)
    /etc/init.d/S41udhcpc stop
    /etc/init.d/S41udhcpc start
  ;;

  reload)
  ;;

  force-reload)
  ;;

  stop)
    echo -n "Stopping DHCP client: udhcpc"
    start-stop-daemon --stop --quiet --exec $DAEMON || echo -n " not running"
    echo "."
  ;;

  renew)
    start-stop-daemon --signal USR1 --stop --quiet --exec $DAEMON || echo -n " not running"
  ;;

  release)
    start-stop-daemon --signal USR2 --stop --quiet --exec $DAEMON || echo -n " not running"
  ;;

  *)
    echo "Usage: /etc/init.d/udhcpc {start|stop|restart|reload|force-reload}"
    exit 1
    ;;
esac

exit 0
