#! /bin/sh
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="httpd-server"
NAME=httpd
DAEMON=/usr/sbin/$NAME
OPTION="-c /etc/httpd.conf -h /var/www"

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

echo $1 >>/tmp/output
case "$1" in
  start)
	echo "Starting $DESC: $NAME"
	start-stop-daemon -S -x $DAEMON -- $OPTION
	echo "."
	;;
  stop) echo -n "Stopping $DESC: $NAME"
	start-stop-daemon -K -q -n $NAME
	echo "."
	;;
  reload|force-reload) echo -n "Reloading $DESC configuration..."
	start-stop-daemon -K -q -n $NAME -s 1
	echo "done."
  ;;
  restart) echo "Restarting $DESC: $NAME"
	$0 stop
	sleep 1
	$0 start
	;;
  *) echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
